# Generated by Django 3.2.3 on 2021-05-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210527_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productkids',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productmen',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productwomen',
            name='price',
            field=models.FloatField(),
        ),
    ]
