# Generated by Django 3.2.3 on 2021-05-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_one',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_two',
        ),
    ]
